version: '2'

services:
  test:
    build:
      context: .
    command: bash -c "flutter analyze --no-pub --preamble .
            && flutter test"
    volumes:
      - ./uni/lib:/app/lib
      - ./uni/test:/app/test
