// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/entities/calendar_event.dart';
import 'model/entities/course.dart';
import 'model/entities/course_units/course_unit.dart';
import 'model/entities/exam.dart';
import 'model/entities/floor_occupation.dart';
import 'model/entities/lecture.dart';
import 'model/entities/meal.dart';
import 'model/entities/news.dart';
import 'model/entities/profile.dart';
import 'model/entities/profile_info.dart';
import 'model/entities/reference.dart';
import 'model/entities/restaurant.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 530425131324335422),
    name: 'CalendarEvent',
    lastPropertyId: const obx_int.IdUid(4, 8425201974706566991),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6382665703867377927),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1456752929405718001),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6512738644323298906),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8425201974706566991),
        name: 'uniqueId',
        type: 6,
        flags: 1,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8766127320748861063),
    name: 'Course',
    lastPropertyId: const obx_int.IdUid(10, 2241126849191212410),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3665390265216484172),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2699231020248079055),
        name: 'festId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6267706101558314419),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2601111797268595146),
        name: 'abbreviation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8320243146135565909),
        name: 'currYear',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 35231472350396415),
        name: 'firstEnrollment',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2382592081549804294),
        name: 'faculty',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4316567919446831375),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4239229779432441373),
        name: 'finishedEcts',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2241126849191212410),
        name: 'currentAverage',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7350415528151845279),
    name: 'CourseUnit',
    lastPropertyId: const obx_int.IdUid(17, 2762582051413565992),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3621357537595052621),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 745379497284273090),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8793728078647237426),
        name: 'abbreviation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3609787927860755678),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8789877611368532341),
        name: 'curricularYear',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 999281738034458755),
        name: 'occurrId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5852839434180085467),
        name: 'semesterCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8606471090830298820),
        name: 'semesterName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9221464053807943631),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3047877808114953070),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6616481768228805953),
        name: 'grade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1155088564660878170),
        name: 'ectsGrade',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4433817947689839240),
        name: 'result',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6722515600875181518),
        name: 'ects',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 738982768682995511),
        name: 'festId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1117492736799219851),
        name: 'schoolYear',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2762582051413565992),
        name: 'dbOccurences',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6264740013149632054),
    name: 'Exam',
    lastPropertyId: const obx_int.IdUid(9, 4100978704342356506),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7927870062061976403),
        name: 'start',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1764251364345465332),
        name: 'finish',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1934465095286727673),
        name: 'id',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5291275696337252017),
        name: 'subjectAcronym',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6050059873492745016),
        name: 'subject',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 390975694419135080),
        name: 'rooms',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1533290708627351393),
        name: 'examType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6301199270529398118),
        name: 'occurrId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4100978704342356506),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8958203706062233220),
    name: 'FloorOccupation',
    lastPropertyId: const obx_int.IdUid(3, 3201979080228518212),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2535080945298351667),
        name: 'number',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7139700621659494979),
        name: 'occupation',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3201979080228518212),
        name: 'capacity',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 8171367879829495835),
    name: 'Lecture',
    lastPropertyId: const obx_int.IdUid(12, 6969316018269244203),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5383871921825150407),
        name: 'uniqueId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 201092000591521938),
        name: 'acronym',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9183402681471116179),
        name: 'subject',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8467713965694326563),
        name: 'typeClass',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3803259491266197706),
        name: 'room',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8040694404057904311),
        name: 'teacher',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3822935314972623459),
        name: 'teacherName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4999211809095154313),
        name: 'teacherId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5209569722892967121),
        name: 'classNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3607372980483634855),
        name: 'startTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2614048377992864604),
        name: 'endTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6969316018269244203),
        name: 'occurrId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 7628085297208106091),
    name: 'Meal',
    lastPropertyId: const obx_int.IdUid(7, 1569316148995165090),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2958329298568204753),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1449986141343205200),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2269786060030172862),
        name: 'namePt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8605035152093888997),
        name: 'nameEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 530560705488605197),
        name: 'dbDayOfWeek',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9009054245949700769),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1569316148995165090),
        name: 'restaurantId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8876662590373252145),
        relationField: 'restaurant',
        relationTarget: 'Restaurant',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 6102888203714718297),
    name: 'News',
    lastPropertyId: const obx_int.IdUid(5, 7746808758803477455),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2589498743617671750),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5250660240398378106),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6222112764075254490),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2636276825790901810),
        name: 'image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7746808758803477455),
        name: 'link',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 4928743523651939869),
    name: 'Profile',
    lastPropertyId: const obx_int.IdUid(7, 9027176496217032455),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4021117406216425917),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6027073199829710882),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4273603378121680460),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7177464874805179896),
        name: 'printBalance',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8464585005346258017),
        name: 'feesBalance',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7123550134298350589),
        name: 'feesLimit',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9027176496217032455),
        name: 'answeredPedagogicalSurveys',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 4155556763398646214),
    name: 'ProfileInfo',
    lastPropertyId: const obx_int.IdUid(6, 7289069097129359773),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 608489470411076437),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8130944735437495208),
        name: 'dbProfileInfo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7192430848830637233),
        name: 'dbNationalities',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1035197482304187710),
        name: 'dbIdentification',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3401020503640784022),
        name: 'dbContacts',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7289069097129359773),
        name: 'dbAddresses',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 152453921604597964),
    name: 'Reference',
    lastPropertyId: const obx_int.IdUid(6, 3467342550910815531),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5938891440526115401),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6858577409898077466),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 984428439819660367),
        name: 'limitDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3310865443950802329),
        name: 'entity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3156375564147692255),
        name: 'reference',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3467342550910815531),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 5587795271338633280),
    name: 'Restaurant',
    lastPropertyId: const obx_int.IdUid(11, 2582329256329520243),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2268363033185952743),
        name: 'uniqueId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2552898432979327101),
        name: 'id',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9081120606152061952),
        name: 'typePt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7379371056630097488),
        name: 'typeEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 625943009229981739),
        name: 'namePt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1457292800651987378),
        name: 'nameEn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 848160823479260009),
        name: 'period',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1785550905992545677),
        name: 'campusId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3239551355494320197),
        name: 'reference',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4974944789261968474),
        name: 'openingHours',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2582329256329520243),
        name: 'email',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'meals',
        srcEntity: 'Meal',
        srcField: 'restaurant',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(12, 5587795271338633280),
    lastIndexId: const obx_int.IdUid(1, 8876662590373252145),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CalendarEvent: obx_int.EntityDefinition<CalendarEvent>(
      model: _entities[0],
      toOneRelations: (CalendarEvent object) => [],
      toManyRelations: (CalendarEvent object) => {},
      getId: (CalendarEvent object) => object.uniqueId,
      setId: (CalendarEvent object, int id) {
        object.uniqueId = id;
      },
      objectToFB: (CalendarEvent object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addOffset(0, nameOffset);
        fbb.addInt64(1, object.startDate?.millisecondsSinceEpoch);
        fbb.addInt64(2, object.endDate?.millisecondsSinceEpoch);
        fbb.addInt64(3, object.uniqueId ?? 0);
        fbb.finish(fbb.endTable());
        return object.uniqueId ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final endDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 4, '');
        final startDateParam = startDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(startDateValue);
        final endDateParam = endDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(endDateValue);
        final object =
            CalendarEvent(
                name: nameParam,
                startDate: startDateParam,
                endDate: endDateParam,
              )
              ..uniqueId = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                10,
              );

        return object;
      },
    ),
    Course: obx_int.EntityDefinition<Course>(
      model: _entities[1],
      toOneRelations: (Course object) => [],
      toManyRelations: (Course object) => {},
      getId: (Course object) => object.id,
      setId: (Course object, int id) {
        object.id = id;
      },
      objectToFB: (Course object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final abbreviationOffset = object.abbreviation == null
            ? null
            : fbb.writeString(object.abbreviation!);
        final currYearOffset = object.currYear == null
            ? null
            : fbb.writeString(object.currYear!);
        final facultyOffset = object.faculty == null
            ? null
            : fbb.writeString(object.faculty!);
        final stateOffset = object.state == null
            ? null
            : fbb.writeString(object.state!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addInt64(1, object.festId);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, abbreviationOffset);
        fbb.addOffset(4, currYearOffset);
        fbb.addInt64(5, object.firstEnrollment);
        fbb.addOffset(6, facultyOffset);
        fbb.addOffset(7, stateOffset);
        fbb.addFloat64(8, object.finishedEcts);
        fbb.addFloat64(9, object.currentAverage);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final festIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final abbreviationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final currYearParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final firstEnrollmentParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final stateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final facultyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final finishedEctsParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final currentAverageParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final object = Course(
          id: idParam,
          festId: festIdParam,
          name: nameParam,
          abbreviation: abbreviationParam,
          currYear: currYearParam,
          firstEnrollment: firstEnrollmentParam,
          state: stateParam,
          faculty: facultyParam,
          finishedEcts: finishedEctsParam,
          currentAverage: currentAverageParam,
        );

        return object;
      },
    ),
    CourseUnit: obx_int.EntityDefinition<CourseUnit>(
      model: _entities[2],
      toOneRelations: (CourseUnit object) => [],
      toManyRelations: (CourseUnit object) => {},
      getId: (CourseUnit object) => object.id,
      setId: (CourseUnit object, int id) {
        object.id = id;
      },
      objectToFB: (CourseUnit object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final abbreviationOffset = fbb.writeString(object.abbreviation);
        final nameOffset = fbb.writeString(object.name);
        final semesterCodeOffset = object.semesterCode == null
            ? null
            : fbb.writeString(object.semesterCode!);
        final semesterNameOffset = object.semesterName == null
            ? null
            : fbb.writeString(object.semesterName!);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        final statusOffset = object.status == null
            ? null
            : fbb.writeString(object.status!);
        final gradeOffset = object.grade == null
            ? null
            : fbb.writeString(object.grade!);
        final ectsGradeOffset = object.ectsGrade == null
            ? null
            : fbb.writeString(object.ectsGrade!);
        final resultOffset = object.result == null
            ? null
            : fbb.writeString(object.result!);
        final schoolYearOffset = object.schoolYear == null
            ? null
            : fbb.writeString(object.schoolYear!);
        final dbOccurencesOffset = object.dbOccurences == null
            ? null
            : fbb.writeString(object.dbOccurences!);
        fbb.startTable(18);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, codeOffset);
        fbb.addOffset(2, abbreviationOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addInt64(4, object.curricularYear);
        fbb.addInt64(5, object.occurrId);
        fbb.addOffset(6, semesterCodeOffset);
        fbb.addOffset(7, semesterNameOffset);
        fbb.addOffset(8, typeOffset);
        fbb.addOffset(9, statusOffset);
        fbb.addOffset(10, gradeOffset);
        fbb.addOffset(11, ectsGradeOffset);
        fbb.addOffset(12, resultOffset);
        fbb.addFloat64(13, object.ects);
        fbb.addInt64(14, object.festId);
        fbb.addOffset(15, schoolYearOffset);
        fbb.addOffset(16, dbOccurencesOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final abbreviationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final occurrIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final curricularYearParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final semesterCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final semesterNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final gradeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final ectsGradeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final resultParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final ectsParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final schoolYearParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final festIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final dbOccurencesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final object = CourseUnit(
          abbreviation: abbreviationParam,
          name: nameParam,
          occurrId: occurrIdParam,
          id: idParam,
          code: codeParam,
          curricularYear: curricularYearParam,
          semesterCode: semesterCodeParam,
          semesterName: semesterNameParam,
          type: typeParam,
          status: statusParam,
          grade: gradeParam,
          ectsGrade: ectsGradeParam,
          result: resultParam,
          ects: ectsParam,
          schoolYear: schoolYearParam,
          festId: festIdParam,
          dbOccurences: dbOccurencesParam,
        );

        return object;
      },
    ),
    Exam: obx_int.EntityDefinition<Exam>(
      model: _entities[3],
      toOneRelations: (Exam object) => [],
      toManyRelations: (Exam object) => {},
      getId: (Exam object) => object.dbId,
      setId: (Exam object, int id) {
        object.dbId = id;
      },
      objectToFB: (Exam object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final subjectAcronymOffset = fbb.writeString(object.subjectAcronym);
        final subjectOffset = fbb.writeString(object.subject);
        final roomsOffset = fbb.writeList(
          object.rooms.map(fbb.writeString).toList(growable: false),
        );
        final examTypeOffset = fbb.writeString(object.examType);
        final occurrIdOffset = fbb.writeString(object.occurrId);
        fbb.startTable(10);
        fbb.addInt64(0, object.start.millisecondsSinceEpoch);
        fbb.addInt64(1, object.finish.millisecondsSinceEpoch);
        fbb.addOffset(2, idOffset);
        fbb.addOffset(3, subjectAcronymOffset);
        fbb.addOffset(4, subjectOffset);
        fbb.addOffset(5, roomsOffset);
        fbb.addOffset(6, examTypeOffset);
        fbb.addOffset(7, occurrIdOffset);
        fbb.addInt64(8, object.dbId ?? 0);
        fbb.finish(fbb.endTable());
        return object.dbId ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
        );
        final finishParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final subjectAcronymParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final roomsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final examTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final occurrIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object =
            Exam(
                idParam,
                startParam,
                finishParam,
                subjectAcronymParam,
                subjectParam,
                roomsParam,
                examTypeParam,
                occurrIdParam,
              )
              ..dbId = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                20,
              );

        return object;
      },
    ),
    FloorOccupation: obx_int.EntityDefinition<FloorOccupation>(
      model: _entities[4],
      toOneRelations: (FloorOccupation object) => [],
      toManyRelations: (FloorOccupation object) => {},
      getId: (FloorOccupation object) => object.number,
      setId: (FloorOccupation object, int id) {
        object.number = id;
      },
      objectToFB: (FloorOccupation object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.number);
        fbb.addInt64(1, object.occupation);
        fbb.addInt64(2, object.capacity);
        fbb.finish(fbb.endTable());
        return object.number;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final numberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final occupationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final capacityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = FloorOccupation(
          numberParam,
          occupationParam,
          capacityParam,
        );

        return object;
      },
    ),
    Lecture: obx_int.EntityDefinition<Lecture>(
      model: _entities[5],
      toOneRelations: (Lecture object) => [],
      toManyRelations: (Lecture object) => {},
      getId: (Lecture object) => object.uniqueId,
      setId: (Lecture object, int id) {
        object.uniqueId = id;
      },
      objectToFB: (Lecture object, fb.Builder fbb) {
        final acronymOffset = fbb.writeString(object.acronym);
        final subjectOffset = fbb.writeString(object.subject);
        final typeClassOffset = fbb.writeString(object.typeClass);
        final roomOffset = fbb.writeString(object.room);
        final teacherOffset = fbb.writeString(object.teacher);
        final teacherNameOffset = fbb.writeString(object.teacherName);
        final classNumberOffset = fbb.writeString(object.classNumber);
        fbb.startTable(13);
        fbb.addInt64(0, object.uniqueId ?? 0);
        fbb.addOffset(1, acronymOffset);
        fbb.addOffset(2, subjectOffset);
        fbb.addOffset(3, typeClassOffset);
        fbb.addOffset(4, roomOffset);
        fbb.addOffset(5, teacherOffset);
        fbb.addOffset(6, teacherNameOffset);
        fbb.addInt64(7, object.teacherId);
        fbb.addOffset(8, classNumberOffset);
        fbb.addInt64(9, object.startTime.millisecondsSinceEpoch);
        fbb.addInt64(10, object.endTime.millisecondsSinceEpoch);
        fbb.addInt64(11, object.occurrId);
        fbb.finish(fbb.endTable());
        return object.uniqueId ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final acronymParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeClassParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final startTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final endTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final roomParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final teacherParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final teacherNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final teacherIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final classNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final occurrIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final object =
            Lecture(
                acronymParam,
                subjectParam,
                typeClassParam,
                startTimeParam,
                endTimeParam,
                roomParam,
                teacherParam,
                teacherNameParam,
                teacherIdParam,
                classNumberParam,
                occurrIdParam,
              )
              ..uniqueId = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                4,
              );

        return object;
      },
    ),
    Meal: obx_int.EntityDefinition<Meal>(
      model: _entities[6],
      toOneRelations: (Meal object) => [object.restaurant],
      toManyRelations: (Meal object) => {},
      getId: (Meal object) => object.id,
      setId: (Meal object, int id) {
        object.id = id;
      },
      objectToFB: (Meal object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final namePtOffset = fbb.writeString(object.namePt);
        final nameEnOffset = fbb.writeString(object.nameEn);
        fbb.startTable(8);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, typeOffset);
        fbb.addOffset(2, namePtOffset);
        fbb.addOffset(3, nameEnOffset);
        fbb.addInt64(4, object.dbDayOfWeek);
        fbb.addInt64(5, object.date.millisecondsSinceEpoch);
        fbb.addInt64(6, object.restaurant.targetId);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final namePtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final dbDayOfWeekParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = Meal(
          typeParam,
          namePtParam,
          nameEnParam,
          dateParam,
          dbDayOfWeek: dbDayOfWeekParam,
        )..id = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
        object.restaurant.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.restaurant.attach(store);
        return object;
      },
    ),
    News: obx_int.EntityDefinition<News>(
      model: _entities[7],
      toOneRelations: (News object) => [],
      toManyRelations: (News object) => {},
      getId: (News object) => object.id,
      setId: (News object, int id) {
        object.id = id;
      },
      objectToFB: (News object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final imageOffset = fbb.writeString(object.image);
        final linkOffset = fbb.writeString(object.link);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, imageOffset);
        fbb.addOffset(4, linkOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final imageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final linkParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = News(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          image: imageParam,
          link: linkParam,
        );

        return object;
      },
    ),
    Profile: obx_int.EntityDefinition<Profile>(
      model: _entities[8],
      toOneRelations: (Profile object) => [],
      toManyRelations: (Profile object) => {},
      getId: (Profile object) => object.id,
      setId: (Profile object, int id) {
        object.id = id;
      },
      objectToFB: (Profile object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final emailOffset = fbb.writeString(object.email);
        final printBalanceOffset = fbb.writeString(object.printBalance);
        final feesBalanceOffset = fbb.writeString(object.feesBalance);
        fbb.startTable(8);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, printBalanceOffset);
        fbb.addOffset(4, feesBalanceOffset);
        fbb.addInt64(5, object.feesLimit?.millisecondsSinceEpoch);
        fbb.addBool(6, object.answeredPedagogicalSurveys);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final feesLimitValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final printBalanceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final feesBalanceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final feesLimitParam = feesLimitValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(feesLimitValue);
        final answeredPedagogicalSurveysParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = Profile(
          name: nameParam,
          email: emailParam,
          printBalance: printBalanceParam,
          feesBalance: feesBalanceParam,
          feesLimit: feesLimitParam,
          answeredPedagogicalSurveys: answeredPedagogicalSurveysParam,
        )..id = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);

        return object;
      },
    ),
    ProfileInfo: obx_int.EntityDefinition<ProfileInfo>(
      model: _entities[9],
      toOneRelations: (ProfileInfo object) => [],
      toManyRelations: (ProfileInfo object) => {},
      getId: (ProfileInfo object) => object.id,
      setId: (ProfileInfo object, int id) {
        object.id = id;
      },
      objectToFB: (ProfileInfo object, fb.Builder fbb) {
        final dbProfileInfoOffset = fbb.writeString(object.dbProfileInfo);
        final dbNationalitiesOffset = fbb.writeString(object.dbNationalities);
        final dbIdentificationOffset = fbb.writeString(object.dbIdentification);
        final dbContactsOffset = fbb.writeString(object.dbContacts);
        final dbAddressesOffset = fbb.writeString(object.dbAddresses);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dbProfileInfoOffset);
        fbb.addOffset(2, dbNationalitiesOffset);
        fbb.addOffset(3, dbIdentificationOffset);
        fbb.addOffset(4, dbContactsOffset);
        fbb.addOffset(5, dbAddressesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dbProfileInfoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dbNationalitiesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dbIdentificationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dbContactsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final dbAddressesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = ProfileInfo(
          id: idParam,
          dbProfileInfo: dbProfileInfoParam,
          dbNationalities: dbNationalitiesParam,
          dbIdentification: dbIdentificationParam,
          dbContacts: dbContactsParam,
          dbAddresses: dbAddressesParam,
        );

        return object;
      },
    ),
    Reference: obx_int.EntityDefinition<Reference>(
      model: _entities[10],
      toOneRelations: (Reference object) => [],
      toManyRelations: (Reference object) => {},
      getId: (Reference object) => object.id,
      setId: (Reference object, int id) {
        object.id = id;
      },
      objectToFB: (Reference object, fb.Builder fbb) {
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(7);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, descriptionOffset);
        fbb.addInt64(2, object.limitDate.millisecondsSinceEpoch);
        fbb.addInt64(3, object.entity);
        fbb.addInt64(4, object.reference);
        fbb.addFloat64(5, object.amount);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final limitDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final entityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final referenceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = Reference(
          descriptionParam,
          limitDateParam,
          entityParam,
          referenceParam,
          amountParam,
        )..id = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);

        return object;
      },
    ),
    Restaurant: obx_int.EntityDefinition<Restaurant>(
      model: _entities[11],
      toOneRelations: (Restaurant object) => [],
      toManyRelations: (Restaurant object) => {
        obx_int.RelInfo<Meal>.toOneBacklink(
          7,
          object.uniqueId!,
          (Meal srcObject) => srcObject.restaurant,
        ): object.meals,
      },
      getId: (Restaurant object) => object.uniqueId,
      setId: (Restaurant object, int id) {
        object.uniqueId = id;
      },
      objectToFB: (Restaurant object, fb.Builder fbb) {
        final typePtOffset = object.typePt == null
            ? null
            : fbb.writeString(object.typePt!);
        final typeEnOffset = object.typeEn == null
            ? null
            : fbb.writeString(object.typeEn!);
        final namePtOffset = fbb.writeString(object.namePt);
        final nameEnOffset = fbb.writeString(object.nameEn);
        final periodOffset = fbb.writeString(object.period);
        final referenceOffset = fbb.writeString(object.reference);
        final openingHoursOffset = fbb.writeList(
          object.openingHours.map(fbb.writeString).toList(growable: false),
        );
        final emailOffset = fbb.writeString(object.email);
        fbb.startTable(12);
        fbb.addInt64(0, object.uniqueId ?? 0);
        fbb.addInt64(1, object.id);
        fbb.addOffset(2, typePtOffset);
        fbb.addOffset(3, typeEnOffset);
        fbb.addOffset(4, namePtOffset);
        fbb.addOffset(5, nameEnOffset);
        fbb.addOffset(6, periodOffset);
        fbb.addInt64(7, object.campusId);
        fbb.addOffset(8, referenceOffset);
        fbb.addOffset(9, openingHoursOffset);
        fbb.addOffset(10, emailOffset);
        fbb.finish(fbb.endTable());
        return object.uniqueId ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final typePtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final typeEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final namePtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final nameEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final periodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final campusIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final referenceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final openingHoursParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 22, []);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object =
            Restaurant(
                idParam,
                typePtParam,
                typeEnParam,
                namePtParam,
                nameEnParam,
                periodParam,
                campusIdParam,
                referenceParam,
                openingHoursParam,
                emailParam,
              )
              ..uniqueId = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                4,
              );
        obx_int.InternalToManyAccess.setRelInfo<Restaurant>(
          object.meals,
          store,
          obx_int.RelInfo<Meal>.toOneBacklink(
            7,
            object.uniqueId!,
            (Meal srcObject) => srcObject.restaurant,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CalendarEvent] entity fields to define ObjectBox queries.
class CalendarEvent_ {
  /// See [CalendarEvent.name].
  static final name = obx.QueryStringProperty<CalendarEvent>(
    _entities[0].properties[0],
  );

  /// See [CalendarEvent.startDate].
  static final startDate = obx.QueryDateProperty<CalendarEvent>(
    _entities[0].properties[1],
  );

  /// See [CalendarEvent.endDate].
  static final endDate = obx.QueryDateProperty<CalendarEvent>(
    _entities[0].properties[2],
  );

  /// See [CalendarEvent.uniqueId].
  static final uniqueId = obx.QueryIntegerProperty<CalendarEvent>(
    _entities[0].properties[3],
  );
}

/// [Course] entity fields to define ObjectBox queries.
class Course_ {
  /// See [Course.id].
  static final id = obx.QueryIntegerProperty<Course>(
    _entities[1].properties[0],
  );

  /// See [Course.festId].
  static final festId = obx.QueryIntegerProperty<Course>(
    _entities[1].properties[1],
  );

  /// See [Course.name].
  static final name = obx.QueryStringProperty<Course>(
    _entities[1].properties[2],
  );

  /// See [Course.abbreviation].
  static final abbreviation = obx.QueryStringProperty<Course>(
    _entities[1].properties[3],
  );

  /// See [Course.currYear].
  static final currYear = obx.QueryStringProperty<Course>(
    _entities[1].properties[4],
  );

  /// See [Course.firstEnrollment].
  static final firstEnrollment = obx.QueryIntegerProperty<Course>(
    _entities[1].properties[5],
  );

  /// See [Course.faculty].
  static final faculty = obx.QueryStringProperty<Course>(
    _entities[1].properties[6],
  );

  /// See [Course.state].
  static final state = obx.QueryStringProperty<Course>(
    _entities[1].properties[7],
  );

  /// See [Course.finishedEcts].
  static final finishedEcts = obx.QueryDoubleProperty<Course>(
    _entities[1].properties[8],
  );

  /// See [Course.currentAverage].
  static final currentAverage = obx.QueryDoubleProperty<Course>(
    _entities[1].properties[9],
  );
}

/// [CourseUnit] entity fields to define ObjectBox queries.
class CourseUnit_ {
  /// See [CourseUnit.id].
  static final id = obx.QueryIntegerProperty<CourseUnit>(
    _entities[2].properties[0],
  );

  /// See [CourseUnit.code].
  static final code = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[1],
  );

  /// See [CourseUnit.abbreviation].
  static final abbreviation = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[2],
  );

  /// See [CourseUnit.name].
  static final name = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[3],
  );

  /// See [CourseUnit.curricularYear].
  static final curricularYear = obx.QueryIntegerProperty<CourseUnit>(
    _entities[2].properties[4],
  );

  /// See [CourseUnit.occurrId].
  static final occurrId = obx.QueryIntegerProperty<CourseUnit>(
    _entities[2].properties[5],
  );

  /// See [CourseUnit.semesterCode].
  static final semesterCode = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[6],
  );

  /// See [CourseUnit.semesterName].
  static final semesterName = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[7],
  );

  /// See [CourseUnit.type].
  static final type = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[8],
  );

  /// See [CourseUnit.status].
  static final status = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[9],
  );

  /// See [CourseUnit.grade].
  static final grade = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[10],
  );

  /// See [CourseUnit.ectsGrade].
  static final ectsGrade = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[11],
  );

  /// See [CourseUnit.result].
  static final result = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[12],
  );

  /// See [CourseUnit.ects].
  static final ects = obx.QueryDoubleProperty<CourseUnit>(
    _entities[2].properties[13],
  );

  /// See [CourseUnit.festId].
  static final festId = obx.QueryIntegerProperty<CourseUnit>(
    _entities[2].properties[14],
  );

  /// See [CourseUnit.schoolYear].
  static final schoolYear = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[15],
  );

  /// See [CourseUnit.dbOccurences].
  static final dbOccurences = obx.QueryStringProperty<CourseUnit>(
    _entities[2].properties[16],
  );
}

/// [Exam] entity fields to define ObjectBox queries.
class Exam_ {
  /// See [Exam.start].
  static final start = obx.QueryDateProperty<Exam>(_entities[3].properties[0]);

  /// See [Exam.finish].
  static final finish = obx.QueryDateProperty<Exam>(_entities[3].properties[1]);

  /// See [Exam.id].
  static final id = obx.QueryStringProperty<Exam>(_entities[3].properties[2]);

  /// See [Exam.subjectAcronym].
  static final subjectAcronym = obx.QueryStringProperty<Exam>(
    _entities[3].properties[3],
  );

  /// See [Exam.subject].
  static final subject = obx.QueryStringProperty<Exam>(
    _entities[3].properties[4],
  );

  /// See [Exam.rooms].
  static final rooms = obx.QueryStringVectorProperty<Exam>(
    _entities[3].properties[5],
  );

  /// See [Exam.examType].
  static final examType = obx.QueryStringProperty<Exam>(
    _entities[3].properties[6],
  );

  /// See [Exam.occurrId].
  static final occurrId = obx.QueryStringProperty<Exam>(
    _entities[3].properties[7],
  );

  /// See [Exam.dbId].
  static final dbId = obx.QueryIntegerProperty<Exam>(
    _entities[3].properties[8],
  );
}

/// [FloorOccupation] entity fields to define ObjectBox queries.
class FloorOccupation_ {
  /// See [FloorOccupation.number].
  static final number = obx.QueryIntegerProperty<FloorOccupation>(
    _entities[4].properties[0],
  );

  /// See [FloorOccupation.occupation].
  static final occupation = obx.QueryIntegerProperty<FloorOccupation>(
    _entities[4].properties[1],
  );

  /// See [FloorOccupation.capacity].
  static final capacity = obx.QueryIntegerProperty<FloorOccupation>(
    _entities[4].properties[2],
  );
}

/// [Lecture] entity fields to define ObjectBox queries.
class Lecture_ {
  /// See [Lecture.uniqueId].
  static final uniqueId = obx.QueryIntegerProperty<Lecture>(
    _entities[5].properties[0],
  );

  /// See [Lecture.acronym].
  static final acronym = obx.QueryStringProperty<Lecture>(
    _entities[5].properties[1],
  );

  /// See [Lecture.subject].
  static final subject = obx.QueryStringProperty<Lecture>(
    _entities[5].properties[2],
  );

  /// See [Lecture.typeClass].
  static final typeClass = obx.QueryStringProperty<Lecture>(
    _entities[5].properties[3],
  );

  /// See [Lecture.room].
  static final room = obx.QueryStringProperty<Lecture>(
    _entities[5].properties[4],
  );

  /// See [Lecture.teacher].
  static final teacher = obx.QueryStringProperty<Lecture>(
    _entities[5].properties[5],
  );

  /// See [Lecture.teacherName].
  static final teacherName = obx.QueryStringProperty<Lecture>(
    _entities[5].properties[6],
  );

  /// See [Lecture.teacherId].
  static final teacherId = obx.QueryIntegerProperty<Lecture>(
    _entities[5].properties[7],
  );

  /// See [Lecture.classNumber].
  static final classNumber = obx.QueryStringProperty<Lecture>(
    _entities[5].properties[8],
  );

  /// See [Lecture.startTime].
  static final startTime = obx.QueryDateProperty<Lecture>(
    _entities[5].properties[9],
  );

  /// See [Lecture.endTime].
  static final endTime = obx.QueryDateProperty<Lecture>(
    _entities[5].properties[10],
  );

  /// See [Lecture.occurrId].
  static final occurrId = obx.QueryIntegerProperty<Lecture>(
    _entities[5].properties[11],
  );
}

/// [Meal] entity fields to define ObjectBox queries.
class Meal_ {
  /// See [Meal.id].
  static final id = obx.QueryIntegerProperty<Meal>(_entities[6].properties[0]);

  /// See [Meal.type].
  static final type = obx.QueryStringProperty<Meal>(_entities[6].properties[1]);

  /// See [Meal.namePt].
  static final namePt = obx.QueryStringProperty<Meal>(
    _entities[6].properties[2],
  );

  /// See [Meal.nameEn].
  static final nameEn = obx.QueryStringProperty<Meal>(
    _entities[6].properties[3],
  );

  /// See [Meal.dbDayOfWeek].
  static final dbDayOfWeek = obx.QueryIntegerProperty<Meal>(
    _entities[6].properties[4],
  );

  /// See [Meal.date].
  static final date = obx.QueryDateProperty<Meal>(_entities[6].properties[5]);

  /// See [Meal.restaurant].
  static final restaurant = obx.QueryRelationToOne<Meal, Restaurant>(
    _entities[6].properties[6],
  );
}

/// [News] entity fields to define ObjectBox queries.
class News_ {
  /// See [News.id].
  static final id = obx.QueryIntegerProperty<News>(_entities[7].properties[0]);

  /// See [News.title].
  static final title = obx.QueryStringProperty<News>(
    _entities[7].properties[1],
  );

  /// See [News.description].
  static final description = obx.QueryStringProperty<News>(
    _entities[7].properties[2],
  );

  /// See [News.image].
  static final image = obx.QueryStringProperty<News>(
    _entities[7].properties[3],
  );

  /// See [News.link].
  static final link = obx.QueryStringProperty<News>(_entities[7].properties[4]);
}

/// [Profile] entity fields to define ObjectBox queries.
class Profile_ {
  /// See [Profile.id].
  static final id = obx.QueryIntegerProperty<Profile>(
    _entities[8].properties[0],
  );

  /// See [Profile.name].
  static final name = obx.QueryStringProperty<Profile>(
    _entities[8].properties[1],
  );

  /// See [Profile.email].
  static final email = obx.QueryStringProperty<Profile>(
    _entities[8].properties[2],
  );

  /// See [Profile.printBalance].
  static final printBalance = obx.QueryStringProperty<Profile>(
    _entities[8].properties[3],
  );

  /// See [Profile.feesBalance].
  static final feesBalance = obx.QueryStringProperty<Profile>(
    _entities[8].properties[4],
  );

  /// See [Profile.feesLimit].
  static final feesLimit = obx.QueryDateProperty<Profile>(
    _entities[8].properties[5],
  );

  /// See [Profile.answeredPedagogicalSurveys].
  static final answeredPedagogicalSurveys = obx.QueryBooleanProperty<Profile>(
    _entities[8].properties[6],
  );
}

/// [ProfileInfo] entity fields to define ObjectBox queries.
class ProfileInfo_ {
  /// See [ProfileInfo.id].
  static final id = obx.QueryIntegerProperty<ProfileInfo>(
    _entities[9].properties[0],
  );

  /// See [ProfileInfo.dbProfileInfo].
  static final dbProfileInfo = obx.QueryStringProperty<ProfileInfo>(
    _entities[9].properties[1],
  );

  /// See [ProfileInfo.dbNationalities].
  static final dbNationalities = obx.QueryStringProperty<ProfileInfo>(
    _entities[9].properties[2],
  );

  /// See [ProfileInfo.dbIdentification].
  static final dbIdentification = obx.QueryStringProperty<ProfileInfo>(
    _entities[9].properties[3],
  );

  /// See [ProfileInfo.dbContacts].
  static final dbContacts = obx.QueryStringProperty<ProfileInfo>(
    _entities[9].properties[4],
  );

  /// See [ProfileInfo.dbAddresses].
  static final dbAddresses = obx.QueryStringProperty<ProfileInfo>(
    _entities[9].properties[5],
  );
}

/// [Reference] entity fields to define ObjectBox queries.
class Reference_ {
  /// See [Reference.id].
  static final id = obx.QueryIntegerProperty<Reference>(
    _entities[10].properties[0],
  );

  /// See [Reference.description].
  static final description = obx.QueryStringProperty<Reference>(
    _entities[10].properties[1],
  );

  /// See [Reference.limitDate].
  static final limitDate = obx.QueryDateProperty<Reference>(
    _entities[10].properties[2],
  );

  /// See [Reference.entity].
  static final entity = obx.QueryIntegerProperty<Reference>(
    _entities[10].properties[3],
  );

  /// See [Reference.reference].
  static final reference = obx.QueryIntegerProperty<Reference>(
    _entities[10].properties[4],
  );

  /// See [Reference.amount].
  static final amount = obx.QueryDoubleProperty<Reference>(
    _entities[10].properties[5],
  );
}

/// [Restaurant] entity fields to define ObjectBox queries.
class Restaurant_ {
  /// See [Restaurant.uniqueId].
  static final uniqueId = obx.QueryIntegerProperty<Restaurant>(
    _entities[11].properties[0],
  );

  /// See [Restaurant.id].
  static final id = obx.QueryIntegerProperty<Restaurant>(
    _entities[11].properties[1],
  );

  /// See [Restaurant.typePt].
  static final typePt = obx.QueryStringProperty<Restaurant>(
    _entities[11].properties[2],
  );

  /// See [Restaurant.typeEn].
  static final typeEn = obx.QueryStringProperty<Restaurant>(
    _entities[11].properties[3],
  );

  /// See [Restaurant.namePt].
  static final namePt = obx.QueryStringProperty<Restaurant>(
    _entities[11].properties[4],
  );

  /// See [Restaurant.nameEn].
  static final nameEn = obx.QueryStringProperty<Restaurant>(
    _entities[11].properties[5],
  );

  /// See [Restaurant.period].
  static final period = obx.QueryStringProperty<Restaurant>(
    _entities[11].properties[6],
  );

  /// See [Restaurant.campusId].
  static final campusId = obx.QueryIntegerProperty<Restaurant>(
    _entities[11].properties[7],
  );

  /// See [Restaurant.reference].
  static final reference = obx.QueryStringProperty<Restaurant>(
    _entities[11].properties[8],
  );

  /// See [Restaurant.openingHours].
  static final openingHours = obx.QueryStringVectorProperty<Restaurant>(
    _entities[11].properties[9],
  );

  /// See [Restaurant.email].
  static final email = obx.QueryStringProperty<Restaurant>(
    _entities[11].properties[10],
  );

  /// see [Restaurant.meals]
  static final meals = obx.QueryBacklinkToMany<Meal, Restaurant>(
    Meal_.restaurant,
  );
}
