targets:
  $default:
      builders:
        mockito|mockBuilder:
          options:
            build_extensions:
              '^test/{{}}.dart': 'test/mocks/{{}}.mocks.dart'
        source_gen:combining_builder:
          options:
            build_extensions:
              '^lib/{{}}.dart' : 'lib/generated/{{}}.g.dart'