# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end

  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    commit_version_bump(xcodeproj: "Runner.xcodeproj")
    add_git_tag
    push_to_git_remote

    app_store_connect_api_key(
      key_id: "B262X978LJ",
      issuer_id: "b94a874d-3888-4b59-a6f9-63c3583b2a7e",
      key_filepath: "./AuthKey_B262X978LJ.p8",
    )

    get_certificates
    get_provisioning_profiles
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
    #slack(message: "Beta build distributed to test flight!")
  end
end
