name: Sync PR

concurrency:
  group: ${{ github.workflow }}/${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - labeled
      - unlabeled

jobs:
  release_version:
    name: Determine current version
    runs-on: ubuntu-latest

    if: ${{ github.head_ref == 'draft-release' }}

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout merge base
        uses: actions/checkout@v5

      - name: Get release version
        id: version
        uses: ./.github/actions/release-version-action
        with:
          bump_type: track

  update_pr_title:
    name: Update PR title
    runs-on: ubuntu-latest

    needs:
      - release_version

    steps:
      - name: Update title
        run: |
          gh pr edit "${{ github.event.pull_request.url }}" \
            --title "release: v${{ needs.release_version.outputs.version }}"
