on: pull_request

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./uni
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.2'

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ github.ref }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-${{ github.ref }}-

      - run: flutter pub get
      - run: flutter analyze --no-pub --preamble .

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./uni
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.2'

      - run: flutter pub get
      - run: flutter test --no-sound-null-safety
